### ISSUE TITLE
Grettings

### ISSUE THREAD

**Issue by Mujirin** [manyang-megantoro/PHP-Snippet#1]
Assaamu'alaikum Bro

**Comment by manyang-megantoro** [comment]
wawa'alaikumsalam

**Comment by manyang-megantoro** [comment]
wa'alaikumsalam

**Comment by Mujirin** [comment]
Ini Ega kan? Aku WA dan Inbok Fb, sepertinya nak aktif. Akhirnya github wkwkwk.
Piye kabare? Saiki neng endi? Ayo meeting online

**Comment by manyang-megantoro** [comment]
Haha iya e aga jarang buka fb, chat fb lagi aja nanti aku buka
